# Generated by Django 5.0.6 on 2024-06-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s3_handler", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="S3LineAudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio_id", models.CharField(max_length=256)),
                ("audio_url", models.CharField(max_length=256)),
                ("user_id", models.CharField(max_length=256)),
                ("timestamp", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="S3LineFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_id", models.CharField(max_length=256)),
                ("file_url", models.CharField(max_length=256)),
                ("user_id", models.CharField(max_length=256)),
                ("timestamp", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="S3LineVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_id", models.CharField(max_length=256)),
                ("video_url", models.CharField(max_length=256)),
                ("user_id", models.CharField(max_length=256)),
                ("timestamp", models.DateTimeField()),
            ],
        ),
    ]
