# Generated by Django 5.0.6 on 2024-06-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("line_bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LineAudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio_url", models.CharField(max_length=256)),
                ("duration_ms", models.IntegerField()),
                ("content_provider", models.CharField(max_length=10)),
                ("source_type", models.CharField(max_length=10)),
                ("reply_token", models.CharField(max_length=100)),
                ("is_redelivery", models.BooleanField()),
                ("user_id", models.CharField(max_length=256)),
                ("webhook_event_id", models.CharField(max_length=256)),
                ("timestamp", models.DateTimeField()),
                ("received_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LineFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_url", models.CharField(max_length=256)),
                ("filename", models.CharField(max_length=100)),
                ("filesize", models.IntegerField()),
                ("content_provider", models.CharField(max_length=10)),
                ("source_type", models.CharField(max_length=10)),
                ("reply_token", models.CharField(max_length=100)),
                ("is_redelivery", models.BooleanField()),
                ("user_id", models.CharField(max_length=256)),
                ("webhook_event_id", models.CharField(max_length=256)),
                ("timestamp", models.DateTimeField()),
                ("received_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LineVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_url", models.CharField(max_length=256)),
                ("preview_image_url", models.CharField(max_length=256)),
                ("duration_ms", models.IntegerField()),
                ("content_provider", models.CharField(max_length=10)),
                ("source_type", models.CharField(max_length=10)),
                ("reply_token", models.CharField(max_length=100)),
                ("is_redelivery", models.BooleanField()),
                ("user_id", models.CharField(max_length=256)),
                ("webhook_event_id", models.CharField(max_length=256)),
                ("timestamp", models.DateTimeField()),
                ("received_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
