# Generated by Django 5.0.6 on 2024-06-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("line_bot", "0002_lineaudio_linefile_linevideo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linevideo",
            name="preview_image_url",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
