# Generated by Django 5.0.6 on 2024-06-30 04:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("line_bot", "0003_alter_linevideo_preview_image_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="linefile",
            old_name="filesize",
            new_name="filesize_bytes",
        ),
    ]
